---
title: "stats: silhouette score, ch, dbi"
output: html_notebook
---

Part 1: stats
```{r}
#install required package
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("FlowSOM") #for flowsom clustering
BiocManager::install("flowCore") #for flowsom clustering
BiocManager::install("cluster") #for silhouette score
BiocManager::install("fpc") #for ch index
BiocManager::install('clv') #for dbi

BiocManager::install('Seurat') #for pca and flowsom visualization
```

```{r}
library(FlowSOM)
library(flowCore)
library(cluster)
library(fpc)
library(clv)

library(Seurat)
```


```{r}

#input file path, change if needed
fileName <-"/Users/shuming/Desktop/SCFCA/input/full_dataset_biexp_aligned_abonly.csv"

csv <- read.csv(fileName)
om <- as.matrix(csv) 
m <- om[1:3000,] #subset (n=3000), comment this to test the whole file
frame <- new("flowFrame", exprs = m) #convert input to flowframe
fs <- ReadInput(frame) #convert flowframe to flowsom object
fs <- BuildSOM(fs,colsToUse=(-1)) #-1 because we are not using "X" column to build SOM
fs <- BuildMST(fs) 
```


```{r}
#based on flowsom, the optimal k number of clusters = 5 for the sample (n=3000) 
metacl <- MetaClustering(fs$map$codes,
"metaClustering_consensus",
max = 15)

unique(metacl[fs$map$mapping[, 1]])
```





```{r}

#a function that calculate 3 stats for k number of clustering
stats <- function(krange){
  si_li <-list()
  ch_li <-list()
  dbi_li <-list()
  
  for (k in krange) {
    
    #clustering, try each k in krange
    metaClustering <- (metaClustering_consensus(fs$map$codes,k = k,seed=42))

    #calculate silhouette score
    si <- silhouette(metaClustering[fs$map$mapping[, 1]],dist(m),)

    si_li[k] <- mean(si[, 3])
    
    #calculate Calinski-Harabasz index
    ch = calinhara(m,metaClustering[fs$map$mapping[, 1]],cn=max(metaClustering[fs$map$mapping[,1]]))
    
    ch_li[k] <- ch
    
    #calculate Davies–Bouldin index
    dbi = clv.Davies.Bouldin(cls.scatt.data(
      m,
      metaClustering[fs$map$mapping[, 1]]),
      intracls = "average",
      intercls = "average"
    )

    dbi_li[k] <- dbi[1]
    } 

  return(list(si_li, ch_li, dbi_li))
}


krange <- 3:15 #range of number of clusters
li = stats(krange)

#silhouette score: ranges from -1  to 1 
#-1: bad clusters  0: neutral, indifferent  1: good clusters
plot(krange, type='b', li[[1]][krange], xlab='Number of clusters', ylab='Average Silhouette Scores', frame=TRUE)

#Calinski-Harabasz index: 
# the highest value is the optimal number of clusters
plot(krange, type='b', li[[2]][krange], xlab='Number of clusters', ylab='Calinski-Harabasz index', frame=TRUE)

#Davies–Bouldin index: minimum score is zero
#the lowest value is the optimal number of clusters
plot(krange, type='b', li[[3]][krange], xlab='Number of clusters', ylab='Davies–Bouldin index', frame=TRUE)

```

Part 2: plot

```{r}
#repeat the first few steps because now we are using the whole dataset, not just a subset (n=3000)
frame <- new("flowFrame", exprs = om) 
fs <- ReadInput(frame) 
fs <- BuildSOM(fs,colsToUse=(-1)) 
fs <- BuildMST(fs) 

#transpose the csv so that seurat object has the right column and row
tm <- t(csv)
rownames(tm) <- colnames(csv)
colnames(tm) <- rownames(csv)


k <- 4 #change number of cluster here
metaClustering <- (metaClustering_consensus(fs$map$codes,k = k,seed=42))

seu <- CreateSeuratObject(tm)
seu <- ScaleData

#do i need to normalize?
# seu <- NormalizeData(seu, normalization.method = "LogNormalize", scale.factor = 10000)

seu <- FindVariableFeatures(seu)

seu <- AddMetaData(object=seu, metadata=metaClustering[fs$map$mapping[,1]], col.name = 'flowSOM')

#dimentionality reduction methods: pca and umap
seu <-RunPCA(seu,seed.use = 42)
seu <- RunUMAP(seu,features=VariableFeatures(seu))

#allow for color labeling
Idents(seu) <- "flowSOM"
```


```{r}
PCAPlot(seu)
```
```{r}
#individual marker shown in PCA 
for (i in VariableFeatures(seu)) {
  
  print(FeaturePlot(object = seu,features=i, reduction="pca"))
} 
```


```{r}
UMAPPlot(seu)
```



```{r}
#individual marker shown in umap 
for (i in VariableFeatures(seu)) {
  print(FeaturePlot(object = seu,features=i,reduction="umap"))
} 
```


```{r}
DoHeatmap(seu, features=VariableFeatures(seu))
```

```{r}
DotPlot(seu, features=VariableFeatures(seu), group.by="flowSOM")
```
