---
title: "R Notebook"
output: html_notebook
---
Temp

```{r}

# load libraries
library(clusterSim) 
library(FlowSOM)
library(flowCore)
library(cluster)
library(fpc)
library(clv)
library(Seurat)
library(dplyr)
library(ggplot2)
library(clustree)
library(reshape2)







outpath <- "/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/PaperFigures/"
# output path for figures
output_path <- "/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/"
# read in files needed:
# data object with clustering done ready to label
seu.q <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outs/clusters/Louvain/Allcellsretros_LouvainSeuratObject200.Rds")
# reference hMO subset annotated
seu.r<- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/PaperFigures/Seu9000annot.08072021.RDS")


```


Seurat label transfer

```{r}
# read in the seurat object with clusters to annotate
# single cell reference mapping
# uses the function TransferData

AB <- c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4")

DimPlot(seu.r)
# this takes long to run - remember to subset the reference matrix
Idents(seu.r) <- 'subgroups'

table(seu.r$subgroups)
seu.r.sub <- subset(x = seu.r, subset = 500)

# find the anchors for label transfer
anchors <- FindTransferAnchors(reference = seu.r, query = seu.q,features = AB ,reference.reduction = "pca", dim= 1:13) 
# this step is computationally intensive and take a long time
# refdata = reference$cell_lables_wanted
predictions <- TransferData(anchorset = anchors, refdata = seu.r$subgroups, dims = 1:10)

seu.q <- AddMetaData(seu.q, metadata = predictions)


  # label transfer in cluster labels

t.lables <- as.data.frame(table(seu.q$RNA_snn_res.1, seu.q$predicted.id))
pr.t.lables <- as.data.frame(prop.table(table(seu.q$RNA_snn_res.1, seu.q$predicted.id)))
t.lables$Freq <- as.double(t.lables$Freq)
# try to make a heatmap


# try bar chart
ggplot(t.lables, aes(y = Freq, x = Var1, fill = Var2)) + geom_bar(position = "stack", stat= "identity")

# find the top 2 in cell in the group

top.labs <- t.lables  %>% group_by(Var1)  %>% top_n(3, Freq)
top.labs

top.lab <- t.lables  %>% group_by(Var1)  %>% top_n(1, Freq)
top.lab






```




