---
title: "R Notebook"
output: html_notebook
---

PhenoID Figures

```{r}
# set up the environment

library(Seurat)
library(dplyr)
library(ggplot2)
library(reshape2)
```

Figure 2 

```{r}

# Figure 2 B 
# heatmap


# figure 2 B - heatmap of 5 cell lines with colours adjusted
seu <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/2Dcells_surface/Figure2/FigureStuff/Flowset_SelectSeuratlabels.Rds")

AB <- c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4")

# read in the data

# see the heatmap

# need to change colours on the DimPlot and will then change in bars for heatmap
cell.colours <- c("dodgerblue3","burlywood3","#009900","red2","mediumpurple2")

DoHeatmap(seu, group.by = "Batch", features = AB, size= 6,slot = "scale.data", group.colors = c("cadetblue","bisque3","darkolivegreen3","darkgoldenrod3","cyan4"), disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 15))




# save the heatmap
outpath = "/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/"

pdf(paste(outpath,"HM_2Dcell_F2B_23082022.pdf",sep=""),width =6, height = 4)
print(DoHeatmap(seu, group.by = "Batch", features = AB, size= 6,slot = "scale.data", group.colors = cell.colours, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 12)))
dev.off()



#Figure 2C
# UMAP with labels
Idents(seu) <- 'Batch'
unique(seu$Batch)

cell.order <- c("Oligo","Astrocytes", "IPSC","Neurons","NPC")
cell.order <- rev(cell.order)
cell.colours <- c("mediumpurple2","dodgerblue3","burlywood3","#009900","red2")

DimPlot(seu, order = cell.order, cols = cell.colours, shuffle = FALSE, raster=TRUE,pt.size = 0.1, label = FALSE) +
  theme(legend.text = element_text(size=24), axis.title.y = element_text(size=24), 
        axis.title.x = element_text(size=24), axis.text.y = element_text(size =24),
        axis.text.x = element_text(size =24))


pdf(paste(outpath,"UMAP_2Dcell_F2B_23082022.pdf",sep=""),width =6, height = 3)
DimPlot(seu, order = cell.order, cols = cell.colours, shuffle = TRUE, raster=FALSE,pt.size = 0.005, label = FALSE) +
  theme(legend.text = element_text(size=12), axis.title.y = element_text(size=12), 
        axis.title.x = element_text(size=12), axis.text.y = element_text(size =12),
        axis.text.x = element_text(size =12))
dev.off()





```


Figure 3

```{r}
# Figure 3A 
# Plot the reference matrix for correlaiton

#Figure 3B 
# run correlation function
# run function in correlation_tests2.R - will be a real function soon

# the function takes the preprocessed output csv (test_path)
# a path to the reference correlation matrix csv (refrence_path)
# a path to save the output csv and plots


reference_path <- "/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/old/correlation/ReferenceMatrix9celltypesOrdered.csv"
output_path <- "/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/Corr/"


test_path <- "/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outsjan20-9000cells/prepro_outsretrotransformed_flowset.csv"
find_correlation(test_path, reference_path, output_path)
# threshold for assigning unknown is R < 0.45
# threshold for double label is R1-R2 < 0.1

# this produces a csv with the Frequencies of each cell type and a csv with the best and second best correlation coefficients
# read in those csv
corr_cell.df <- read.csv("/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/Corr/corr_celltypes.csv")
freq.df <- read.csv("/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/Corr/Frequencytabletypes.csv")


# plot the main groups - but the correlation co-efficient for the assigned group
df <- corr_cell.df %>% filter(!grepl('-',cell.label))


ggplot(df, aes(x=cell.label, y=cor.1 ))+ geom_violin()+ ylim(-0.1,1)+theme_classic()+
   theme(axis.text.x=element_text(angle=90)) + ylab("correlation coefficient") + xlab("Cell type with max correlation coefficient")


thresh1 <- 0.45
ggplot(df, aes(x=best.cell.type, y=cor.1, fill = best.cell.type))+ geom_violin(trim = FALSE)+ ylim(0,1)+theme_classic()+
   theme(text = element_text(size = 18), axis.text.x=element_text(angle=90, size = 15)) + ylab("correlation coefficient") + xlab("Cell type with max correlation coefficient") +
  geom_hline(yintercept = thresh1) +
  guides(fill = guide_legend(title = "Cell Phenotype"))

#save this plot for figure 3B
pdf(paste(output_path,"Vln.max.cor.main.cells.pdf"),height = 4, width = 6)
ggplot(df, aes(x=best.cell.type, y=cor.1, fill = best.cell.type))+ geom_violin(trim = FALSE)+ ylim(0,1)+theme_classic()+
   theme(text = element_text(size = 15), axis.text.x=element_text(angle=90, size = 12)) + ylab("correlation coefficient") + xlab("Cell type with max correlation coefficient") +
  geom_hline(yintercept = thresh1) +
  guides(fill = guide_legend(title = "Cell Phenotype"))
dev.off()


# Figure 3 C - bar chart of the frequency of assigned cell types with cut-off freq 400
## remove the unknown cell types
df <- corr_cell.df
df.filter <- df %>% filter(!grepl('unknown',cell.label))
# filter for only frequent double cell types
df.filter <- df.filter %>% group_by(cell.label) %>% dplyr::filter(n()> 400)

pdf(paste(output_path,"BarFreq.known400plus.pdf",sep=""),width =6, height = 4)
  plot1 <- ggplot(df.filter, aes(x=reorder(cell.label,cell.label,function(x)-length(x)), fill = cell.label))+ geom_bar()+theme_classic() +
   theme(text = element_text(size = 16), axis.text.x=element_text(angle=90, hjust = 1))+ xlab('Assigned cell type') + ylab('Number of cells') +
    guides(fill = guide_legend(title = "Cell Phenotype")) 
  print(plot1)
dev.off()




```


Figure 3 clustering

This is with the subsample of 9000 cells per hMO

```{r}
# read in the seurat objects
seu <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outsjan20-9000cells/Figure3/cluster_parameters/retro-louv-moreparm/retrotransLouvainSeuratObject60.Rds")
AB <- c("CD24","CD56","CD71","CD29","CD15", "CD184","CD133", "GLAST","CD44","AQP4","HepaCAM","CD140a", "O4" )


# the highest Rand Index are res = 0.1, 7 clusters, res = 0.15, 9 clusters.  Both very low RI std.
# the high RI with low std is 0.3 and 0.7, cluster numbers also have low std 
# from bootstrap 100X
# annotation is easier with 18-25 clusters 

seu <- RunUMAP(seu,spread = 1, min.dist = 0.05, dims = 1:12)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'RNA_snn_res.0.1', repel = TRUE)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'RNA_snn_res.0.15', repel = TRUE)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'RNA_snn_res.0.3', repel = TRUE)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'RNA_snn_res.0.7', repel = TRUE)



# annotate cells 
Idents(seu) <- "RNA_snn_res.0.7"
cluster.ids <- c("LowLabel","Neuron-Glia","Neurons1","RG1","Epi1","Epi-Astro","Neu-OPC","RG-Astro",
                 "Astro","Astro-m","Neurons2","Mix-early-Neu","RG2","RG3","endo","oligo","stem-epi","stem",
                 "neuralstem")

names(cluster.ids) <- levels(seu)
seu <- RenameIdents(seu, cluster.ids)
seu$labels <- Idents(seu)




Idents(seu) <- "RNA_snn_res.0.7"
cluster.ids <- c("Unknown","Mixed","Neurons 1","Radial Glia 1","Epithelial","Astrocytes 1","Neurons 2","Astrocytes 1",
                 "Astrocytes 1","Astrocytes 2","Neurons 2","NPC","Radial Glia 2",
                 "Radial Glia 2","Endothelial","Oligodendrocytes","Stem cell like","Stem cell like",
                 "Stem cell like")

names(cluster.ids) <- levels(seu)
seu <- RenameIdents(seu, cluster.ids)
seu$cell.types <- Idents(seu)

DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'cell.types', repel = TRUE)
# there are 13 levels in the cell type annatotion with major groups

# change the order of the cell types on the legend of the umap
cell.type.order <- c("Astrocytes 1", "Astrocytes 2","Radial Glia 1","Radial Glia 2",
                     "Epithelial","Endothelial","NPC","Neurons 1","Neurons 2",
                     "Oligodendrocytes","Stem cell like","Mixed","Unknown")
cell.type.order <- rev(cell.type.order)

# colour order to match cell type order
clust.colours <- c("chocolate1","orange","lightsalmon", "pink",
                   "steelblue3","deepskyblue","plum3","purple","orchid2",
                   "seagreen3","tomato3","burlywood3","grey90")
                   
                   
 #                  "plum1","purple","magenta3","mediumpurple1","darkorchid","plum3",
#             "steelblue3","darkorange1","orange1","lightcoral","coral1","orangered1","lightsalmon",
 #            "cyan")

# Figure 3D UMAP with annotated clusters
output_path <- "/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/"

png(paste(output_path,"UMAPlabelled9000.08072022.png"),width = 1000, height = 500)
DimPlot(seu, order = cell.type.order, cols = clust.colours, shuffle = TRUE, raster=TRUE,pt.size = 0.1, label = FALSE) +
  theme(legend.text = element_text(size=24), axis.title.y = element_text(size=24), 
        axis.title.x = element_text(size=24), axis.text.y = element_text(size =24),
        axis.text.x = element_text(size =24))
dev.off()

png(paste(output_path,"UMAPlabelled9000.08072022.norater.png"),width = 1100, height = 600)
DimPlot(seu, order = cell.type.order, cols = clust.colours, shuffle = TRUE, raster=FALSE,pt.size = 0.05, label = FALSE) +
  theme(legend.text = element_text(size=24), axis.title.y = element_text(size=24), 
        axis.title.x = element_text(size=24), axis.text.y = element_text(size =24),
        axis.text.x = element_text(size =24))
dev.off()

# use PDF for figure for correct resolution
pdf(paste(output_path,"UMAPlabelled9000.08072022.noraster.pdf"),width = 10, height = 5)
DimPlot(seu, order = cell.type.order, cols = clust.colours, shuffle = TRUE, raster=FALSE,pt.size = 0.1, label = FALSE) +
  theme(legend.text = element_text(size=24), axis.title.y = element_text(size=24), 
        axis.title.x = element_text(size=24), axis.text.y = element_text(size =24),
        axis.text.x = element_text(size =24))
dev.off()

DimPlot(seu, order = cell.type.order, cols = clust.colours, shuffle = TRUE, raster=FALSE,pt.size = 0.1, label = TRUE)

# save the annotated object

saveRDS(seu, "/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/PaperFigures/Seu9000annot.08072021.RDS")


######## figure 3E heatmap of the 

# reorder the bars to match the UMAP
levels(seu) <- c("Astrocytes 1", "Astrocytes 2","Radial Glia 1","Radial Glia 2",
                     "Epithelial","Endothelial","NPC","Neurons 1","Neurons 2",
                     "Oligodendrocytes","Stem cell like","Mixed","Unknown")

pdf(paste(output_path,"HM9000.08072022.pdf"),width = 8, height = 5)
DoHeatmap(seu, features = AB, size= 6,slot = "scale.data", group.colors = clust.colours, disp.max = 2, disp.min = -1.5,
          angle = 90) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 15))
dev.off()


```







