---
title: "Visualize reference matrix"
output: html_notebook
---


```{r}
library(dplyr)
library(ggplot2)
library(reshape)

```



```{r}
# read in the reference matrix
# then plot each matrix with this script
ref <- read.csv("/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/correlation/ReferenceMatrix.csv")

ref
ref$X
colnames(ref)

# filter the matrix to remove microglia
A <- ref %>% slice(1:10)



# filter out the pericytes

A <- ref %>% slice(1:8,10)
print(head(A))

# save matrix without pericytes
#write.csv(A,"/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/correlation/ReferenceMatrix9celltypes.csv", row.names = FALSE)
# check if it save correctly
#A2 <- read.csv("/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/correlation/ReferenceMatrix9celltypes.csv")
# it did

# reorder AB
A <- A %>% select(c("X","CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","Glast","AQP4","HepaCam", "CD140a","O4"))

# rename some columns to keep consistent names
col.names <- c("X","CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4")

names(A) <- col.names
write.csv(A,"/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/correlation/ReferenceMatrix9celltypesOrdered.csv", row.names = FALSE)

# z-scale in the same way as for the correlation test
B<- A %>% select(c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4"))
X <- A$X
B<- as.data.frame(scale(B))
B<- cbind(X,B)


write.csv(B,"/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/correlation/ReferenceMatrix9scaled.csv", row.names = FALSE)

A<- B

```

Plots

```{r}

# replace NaN with 0
class(A)
#x <- replace(A, is.na(A), 0)

# library reshape has function melt
# takes the table format and makes it into the format needed for plotting
longData<- melt(A)

longData<- melt(B)
# try to remove rows NaN
#longData<-longData[longData$value!=0,]
ggplot(longData, aes(x = variable, y = X)) + 
  geom_raster(aes(fill=value)) + 
  scale_fill_gradient(low="grey90", high="red", na.value = "grey") +
  labs(x="Antibodies", y="Cell Types", title="Matrix") +
  theme_bw() + theme(axis.text.x=element_text(size=12, angle=90, vjust=0.3),
                     axis.text.y=element_text(size=12),
                     plot.title=element_text(size=12))

longData$variable <- as.factor(longData$variable)

pdf("/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/ReferenceMatrix9cellScaled.pdf", width = 5, height = 4)
ggplot(longData, aes(x = X, y = variable)) + 
  geom_raster(aes(fill=value)) + 
  scale_fill_gradient(low="grey90", high="red", na.value = "grey") + scale_x_discrete(position = "top")+ scale_y_discrete(limits = rev) +
  labs(x="Cell Types", y= "Antibodies")  + theme_classic() +  theme(axis.line = element_blank()) +
   theme(axis.text.x=element_text(size=12, angle=90, vjust=0.3, colour = 'black'),
                     axis.text.y=element_text(size=12, color = 'black'))
dev.off()



```



