---
title: "R Notebook"
output: html_notebook
---


```{r}
# load libraries
# load libraries
library(clusterSim) 
library(FlowSOM)
library(flowCore)
library(cluster)
library(fpc)
library(clv)
library(Seurat)
library(dplyr)
library(ggplot2)
library(clustree)
library(reshape2)

```





Visialize correlations on UMAP

```{r}
# read in correlation



# read in Seurat object to make UMAP
seu <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outsjan20-9000cells/Figure3/cluster_parameters/retro-louv-moreparm/retrotransLouvainSeuratObject60.Rds")

# Feature list
# "AQP4"    "CD24"    "CD44"    "CD184"   "CD15"    "HepaCAM" "CD29"    "CD56"    "O4"      "CD140a" 
# "CD133"   "GLAST"   "CD71"  

AB <- c("CD24","CD56","CD71","CD29","CD15", "CD184","CD133", "GLAST","CD44","AQP4","HepaCAM","CD140a", "O4" )




```


Add the cell labels into seurat object

```{r}

seu <- AddMetaData(object=seu, metadata=df$cell.label, col.name = 'cor.labels')
```




Make UMAP


```{r}
seu <- RunUMAP(seu,spread = 2, min.dist = 0.1, dims = 1:12)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'cor.labels', repel = TRUE)





```


Save UMAPS

```{r}

outpath <- "/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outsjan20-9000cells/Figure3/"

pdf(paste(outpath,"UMAPlouvk60res02CorLables8celltypes.pdf"), width = 20, height = 8)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'cor.labels', repel = TRUE)
dev.off()


# save the clusters

#pdf(paste(outpath,"UMAPlouvk60res02Clusters.pdf"), width = 20, height = 8)
#DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'RNA_snn_res.0.5', repel = TRUE)
#dev.off()


```


```{r}
# save feature plot with new UMAP structure and better dimensions
pdf(paste(outpath,"UMAPlouvk60res02FeaturePlots.pdf"), width = 20, height = 8)
FeaturePlot(seu, reduction = "umap", features = AB,slot = 'scale.data',min.cutoff = 'q1', max.cutoff ='99',label.size = 1)+ theme(plot.title = element_text(size = 0.1))
dev.off()

FeaturePlot(seu, reduction = "umap", features = AB,slot = 'scale.data',label.size = 1)+ theme(plot.title = element_text(size = 0.1))




```


Add labels

0-Neurons-e
1-Neurons
2-Astro-1
3-Neurons-e
4-RG1
5-Endothelial
6-Astro-2
7-Astro-oligo
8-Astro-early
9-Endothelial
10-RG2
11-Glia
12-Oligo
13-OPC
14-stem
15-NPC




```{r}
Idents(seu) <- "RNA_snn_res.0.5"
cluster.ids <- c("Neurons-e","Neurons","Astro-1","Neurons-e2","RG1","Endothelial","Astro-2","Astro-oligo","Astro-early","Endothelial","RG2","Glia","Oligo","OPC","Stem","NPC")

names(cluster.ids) <- levels(seu)
seu <- RenameIdents(seu, cluster.ids)
seu$labels <- Idents(seu)

DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'labels', repel = TRUE)

# few labels

Idents(seu) <- "RNA_snn_res.0.5"
cluster.ids <- c("Neurons","Neurons","Astro","Neurons","RG1","Endothelial","Astro","Astro","Astro","Endothelial","RG","Glia","Oligo","OPC","Stem","NPC")

names(cluster.ids) <- levels(seu)
seu <- RenameIdents(seu, cluster.ids)
seu$labels2 <- Idents(seu)

DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'labels2', repel = TRUE)


Idents(seu) <- "RNA_snn_res.0.5"
cluster.ids <- c("Neurons","Neurons","Astro-1","Neurons-e","RG1","Endothelial-1","Astro-2","Astro-1","RGa","Endothelial-2","RG2","Glia","Oligo","OPC","Stem","NPC")

names(cluster.ids) <- levels(seu)
seu <- RenameIdents(seu, cluster.ids)
seu$labels3 <- Idents(seu)


Idents(seu) <- "RNA_snn_res.0.5"
cluster.ids <- c("Neurons-1","Neurons-2","Astro-1","Neurons-e","RG1","Endothelial-1","Astro-2","Astro-1","RGa","Endothelial-2","RG2","Glia","Oligo","OPC","Stem","NPC")

names(cluster.ids) <- levels(seu)
seu <- RenameIdents(seu, cluster.ids)
seu$labels4 <- Idents(seu)




```


Review UMAP parm

```{r}
seu <- RunUMAP(seu,spread = 1, min.dist = 0.5, dims = 1:12)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'RNA_snn_res.0.5', repel = TRUE)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'labels2', repel = TRUE)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'cor.labels', repel = TRUE)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'labels', repel = TRUE)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'labels3', repel = TRUE)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'RNA_snn_res.0.2', repel = TRUE)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'labels4', repel = TRUE)

```

```{r}
# save the labelled seurat object to apply labels to other clustering
# use an inputs to Random Forest
saveRDS(seu,"/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outsjan20-9000cells/Figure3/Louvkn60DifferentCellLabels09032022.Rds")


# save some plots
pdf(paste(outpath,"UMAPlouvk60celltypeLable4.pdf"), width = 8, height = 5)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'labels4', repel = TRUE, shuffle = TRUE, label.size = 5)
dev.off()

pdf(paste(outpath,"UMAPlouvk60cor.label09032022.pdf"), width = 20, height = 8)
DimPlot(seu, reduction = "umap", label = TRUE, group.by = 'cor.labels', repel = TRUE)
dev.off()


DoHeatmap(seu, features = AB, group.by = 'labels4')

pdf(paste(outpath,"HeatMapcelltypeLable4.pdf"), width = 8, height = 5)
DoHeatmap(seu, group.by = 'labels4', features = AB, size= 5,slot = "scale.data", disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 15))
dev.off()


```

