---
title: "R Notebook"
output: html_notebook
---


```{r}
#set up environment
library(Seurat)
library(dplyr)
library(ggplot2)

```


Preprocessing of MO samples 

```{r}

output_path <- "/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/"

input_name <- "cat"  # processing type for file name
clust_method <- "Louvain" # cluster type for file name

input_path <- "/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/Old/preprocessing/outputs/prepro_outsflowset.csv"
df <- read.csv(input_path) # read in the dataframe

# create a df with just the expression
# need a way to automate this selection
# I only want the expression values
df2 <- df %>% dplyr::select(c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4"))


# the order of the DF is set by the order the columns are written above
# create a matrix for later
m <- as.matrix(df2)

# create the seurat object for visualization
tm <- t(df2)
rownames(tm) <- colnames(df2)
colnames(tm) <- rownames(df2)
seu <- CreateSeuratObject(tm)

df$Batch <- as.factor(df$Batch) # so that when added to seurat object batch has levels
# add the meta data back in for sample groups
seu <- AddMetaData(object=seu, metadata=df$Batch, col.name = 'Sample')
# create the vector for the antibodies names for feature plotting later
AB <- colnames(df2)
# add to scale data slot
seu <- ScaleData(seu)
Idents(seu) <- 'Sample'

# see the plot
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
  
# save the plot
png(paste(output_path,"HM_concat.png"), height = 300, width = 400)
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
dev.off()

# create PCA 
seu <- RunPCA(seu, features = AB, npcs = 12, approx = FALSE)
seu <- FindNeighbors(seu, dims = 1:12, k.param = 60)
seu <- FindClusters(seu, resolution = 0.2)
seu <- RunUMAP(seu, dims = 1:12, n.neighbors = 60L)

DimPlot(seu, reduction = "umap")

DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))


png(paste(output_path,"UMAP_concat.png"), height = 300, width = 400)
DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))
dev.off()

########## transform without retro transform

input_name <- "trans"  # processing type for file name
clust_method <- "Louvain" # cluster type for file name

input_path <- "/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/Old/preprocessing/outputs/prepro_outstransformed_flowset.csv"
df <- read.csv(input_path) # read in the dataframe

# create a df with just the expression
# need a way to automate this selection
# I only want the expression values
df2 <- df %>% dplyr::select(c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4"))


# the order of the DF is set by the order the columns are written above
# create a matrix for later
m <- as.matrix(df2)

# create the seurat object for visualization
tm <- t(df2)
rownames(tm) <- colnames(df2)
colnames(tm) <- rownames(df2)
seu <- CreateSeuratObject(tm)

df$Batch <- as.factor(df$Batch) # so that when added to seurat object batch has levels
# add the meta data back in for sample groups
seu <- AddMetaData(object=seu, metadata=df$Batch, col.name = 'Sample')
# create the vector for the antibodies names for feature plotting later
AB <- colnames(df2)
# add to scale data slot
seu <- ScaleData(seu)
Idents(seu) <- 'Sample'

# see the plot
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
  
# save the plot
png(paste(output_path,"HM_trans.png"), height = 300, width = 400)
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
dev.off()

# create PCA 
seu <- RunPCA(seu, features = AB, npcs = 12, approx = FALSE)
seu <- FindNeighbors(seu, dims = 1:12, k.param = 60)
seu <- FindClusters(seu, resolution = 0.2)
seu <- RunUMAP(seu, dims = 1:12, n.neighbors = 60L)

DimPlot(seu, reduction = "umap")

DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))

png(paste(output_path,"UMAP_trans.png"), height = 300, width = 400)
DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))
dev.off()

########## transform and retro transform #############

input_name <- "retro"  # processing type for file name
clust_method <- "Louvain" # cluster type for file name

input_path <- "/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/Old/preprocessing/outputs/prepro_outsretrotransformed_flowset.csv"
df <- read.csv(input_path) # read in the dataframe

# create a df with just the expression
# need a way to automate this selection
# I only want the expression values
df2 <- df %>% dplyr::select(c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4"))


# the order of the DF is set by the order the columns are written above
# create a matrix for later
m <- as.matrix(df2)

# create the seurat object for visualization
tm <- t(df2)
rownames(tm) <- colnames(df2)
colnames(tm) <- rownames(df2)
seu <- CreateSeuratObject(tm)

df$Batch <- as.factor(df$Batch) # so that when added to seurat object batch has levels
# add the meta data back in for sample groups
seu <- AddMetaData(object=seu, metadata=df$Batch, col.name = 'Sample')
# create the vector for the antibodies names for feature plotting later
AB <- colnames(df2)
# add to scale data slot
seu <- ScaleData(seu)
Idents(seu) <- 'Sample'

# see the plot
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
  
# save the plot
png(paste(output_path,"HM_retro.png"), height = 300, width = 400)
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
dev.off()

# create PCA 
seu <- RunPCA(seu, features = AB, npcs = 12, approx = FALSE)
seu <- FindNeighbors(seu, dims = 1:12, k.param = 60)
seu <- FindClusters(seu, resolution = 0.2)
seu <- RunUMAP(seu, dims = 1:12, n.neighbors = 60L)

DimPlot(seu, reduction = "umap")

DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))

png(paste(output_path,"UMAP_retro.png"), height = 300, width = 400)
DimPlot(seu, reduction = "umap", group.by = 'Sample', shuffle = TRUE, cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))
dev.off()




```

