---
title: "R Notebook"
output: html_notebook
---

PhenoID supplemental Figures

S1 - heatmap of 9 MBO samples

```{r}
# Figure S1 
# heatmap of all 9 samples


# S1
# set up the environment 

library(Seurat)
library(dplyr)
library(ggplot2)
library(reshape2)

# read in the annotated data ojbect
seu <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outs/clusters/AllcellLablesMarch25.Rds")

AB <- c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4")

Idents(seu) <- 'Batch'
seu.sub <- subset(x= seu, downsample = 500)
#DoHeatmap(seu.sub, features = AB.order, group.by = "Batch")

DoHeatmap(seu.sub, group.by = "Batch", features = AB, size= 6,slot = "scale.data", group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"), 
          disp.max = 1.5, disp.min = -1.1) + 
  scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 10))


# save
outpath = "/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/"
pdf(paste(outpath,"HM9hMOs.pdf",sep = ""))
DoHeatmap(seu.sub, group.by = "Batch", features = AB, size= 6,slot = "scale.data", group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"), 
          disp.max = 1.5, disp.min = -1.1) + 
  scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 10))
dev.off()




```


S8 - UMAPs and heatmaps from 3 pre-processing methods


```{r}
# 
output_path <- "/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/"

input_name <- "cat"  # processing type for file name
clust_method <- "Louvain" # cluster type for file name

input_path <- "/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/Old/preprocessing/outputs/prepro_outsflowset.csv"
df <- read.csv(input_path) # read in the dataframe

# create a df with just the expression
# need a way to automate this selection
# I only want the expression values
df2 <- df %>% dplyr::select(c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4"))


# the order of the DF is set by the order the columns are written above
# create a matrix for later
m <- as.matrix(df2)

# create the seurat object for visualization
tm <- t(df2)
rownames(tm) <- colnames(df2)
colnames(tm) <- rownames(df2)
seu <- CreateSeuratObject(tm)

df$Batch <- as.factor(df$Batch) # so that when added to seurat object batch has levels
# add the meta data back in for sample groups
seu <- AddMetaData(object=seu, metadata=df$Batch, col.name = 'Sample')
# create the vector for the antibodies names for feature plotting later
AB <- colnames(df2)
# add to scale data slot
seu <- ScaleData(seu)
Idents(seu) <- 'Sample'

# see the plot
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
  
# save the plot
png(paste(output_path,"HM_concat.png"), height = 300, width = 400)
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
dev.off()

# create PCA 
seu <- RunPCA(seu, features = AB, npcs = 12, approx = FALSE)
seu <- FindNeighbors(seu, dims = 1:12, k.param = 60)
seu <- FindClusters(seu, resolution = 0.2)
seu <- RunUMAP(seu, dims = 1:12, n.neighbors = 60L)

DimPlot(seu, reduction = "umap")

DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))


png(paste(output_path,"UMAP_concat.png"), height = 300, width = 400)
DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))
dev.off()

########## transform without retro transform

input_name <- "trans"  # processing type for file name
clust_method <- "Louvain" # cluster type for file name

input_path <- "/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/Old/preprocessing/outputs/prepro_outstransformed_flowset.csv"
df <- read.csv(input_path) # read in the dataframe

# create a df with just the expression
# need a way to automate this selection
# I only want the expression values
df2 <- df %>% dplyr::select(c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4"))


# the order of the DF is set by the order the columns are written above
# create a matrix for later
m <- as.matrix(df2)

# create the seurat object for visualization
tm <- t(df2)
rownames(tm) <- colnames(df2)
colnames(tm) <- rownames(df2)
seu <- CreateSeuratObject(tm)

df$Batch <- as.factor(df$Batch) # so that when added to seurat object batch has levels
# add the meta data back in for sample groups
seu <- AddMetaData(object=seu, metadata=df$Batch, col.name = 'Sample')
# create the vector for the antibodies names for feature plotting later
AB <- colnames(df2)
# add to scale data slot
seu <- ScaleData(seu)
Idents(seu) <- 'Sample'

# see the plot
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
  
# save the plot
png(paste(output_path,"HM_trans.png"), height = 300, width = 400)
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
dev.off()

# create PCA 
seu <- RunPCA(seu, features = AB, npcs = 12, approx = FALSE)
seu <- FindNeighbors(seu, dims = 1:12, k.param = 60)
seu <- FindClusters(seu, resolution = 0.2)
seu <- RunUMAP(seu, dims = 1:12, n.neighbors = 60L)

DimPlot(seu, reduction = "umap")

DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))

png(paste(output_path,"UMAP_trans.png"), height = 300, width = 400)
DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))
dev.off()

########## transform and retro transform #############

input_name <- "retro"  # processing type for file name
clust_method <- "Louvain" # cluster type for file name

input_path <- "/Users/rhalenathomas/GITHUB/PhenoID_single_cell_flow_cytometry_analysis/Old/preprocessing/outputs/prepro_outsretrotransformed_flowset.csv"
df <- read.csv(input_path) # read in the dataframe

# create a df with just the expression
# need a way to automate this selection
# I only want the expression values
df2 <- df %>% dplyr::select(c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4"))


# the order of the DF is set by the order the columns are written above
# create a matrix for later
m <- as.matrix(df2)

# create the seurat object for visualization
tm <- t(df2)
rownames(tm) <- colnames(df2)
colnames(tm) <- rownames(df2)
seu <- CreateSeuratObject(tm)

df$Batch <- as.factor(df$Batch) # so that when added to seurat object batch has levels
# add the meta data back in for sample groups
seu <- AddMetaData(object=seu, metadata=df$Batch, col.name = 'Sample')
# create the vector for the antibodies names for feature plotting later
AB <- colnames(df2)
# add to scale data slot
seu <- ScaleData(seu)
Idents(seu) <- 'Sample'

# see the plot
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
  
# save the plot
png(paste(output_path,"HM_retro.png"), height = 300, width = 400)
DoHeatmap(seu, group.by = 'Sample', features = AB, size= 5,slot = "scale.data",
        angle = 90, group.colors = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"),label = FALSE,
        hjust = 0, group.bar.height = 0.05, disp.max = 2, disp.min = -1.5) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 13)) 
dev.off()

# create PCA 
seu <- RunPCA(seu, features = AB, npcs = 12, approx = FALSE)
seu <- FindNeighbors(seu, dims = 1:12, k.param = 60)
seu <- FindClusters(seu, resolution = 0.2)
seu <- RunUMAP(seu, dims = 1:12, n.neighbors = 60L)

DimPlot(seu, reduction = "umap")

DimPlot(seu, reduction = "umap", group.by = 'Sample', cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))

png(paste(output_path,"UMAP_retro.png"), height = 300, width = 400)
DimPlot(seu, reduction = "umap", group.by = 'Sample', shuffle = TRUE, cols = c("cadetblue1","cadetblue2","cadetblue3", "bisque1","bisque2","bisque3","darkolivegreen1","darkolivegreen2","darkolivegreen3"))+ 
  theme(axis.text.y = element_text(size = 12),axis.text.x = element_text(size = 12))
dev.off()




```


Figure 3 related Sup
Correlation 

```{r}
output_path <- "/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/Corr/"

# read in correlation output
corr_cell.df <- read.csv("/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/Corr/corr_celltypes.csv")
freq.df <- read.csv("/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/Corr/Frequencytabletypes.csv")
# plot the main groups - but the correlation co-efficient for the assigned group
df <- corr_cell.df %>% filter(!grepl('-',cell.label))

# figure S9A 
# showing the assigned cell types main cell types only
pdf(paste(output_path,"Vln.cor.assigned.pdf"),height = 4, width = 10)
ggplot(df, aes(x=cell.label, y=cor.1, fill = best.cell.type))+ geom_violin(trim = FALSE)+ ylim(0,1)+theme_classic()+
   theme(text = element_text(size = 15), axis.text.x=element_text(angle=90, size = 12)) + ylab("correlation coefficient") + xlab("Assigned Cell Type") +
  guides(fill = guide_legend(title = "Cell Phenotype"))
dev.off()

# figure S9B
# box plot of assigned cell type correlation with 
pdf(paste(output_path,"box.cor.alltypes.assign.pdf"),height = 4, width = 10)
ggplot(corr_cell.df, aes(x=cell.label, y=cor.1))+ geom_boxplot()+ ylim(0,1)+theme_classic()+
   theme(text = element_text(size = 15), axis.text.x=element_text(angle=90, size = 12)) + ylab("correlation coefficient") + xlab("Assigned Cell Type") +
  guides(fill = guide_legend(title = "Cell Phenotype")) 
dev.off()

## Figure S10 and S11 connected columns are in the functions and saved from there


## frequency bar charts
df <- corr_cell.df

# remove different elements --- must have at least 100 cells
 df.filter <- df %>% group_by(cell.label) %>% dplyr::filter(n()> 100)
  # # plot
  pdf(paste(output_path,"FreqCellTypes2.pdf",sep=""),width =12, height = 6)
  plot1 <- ggplot(df.filter, aes(x=reorder(cell.label,cell.label,function(x)-length(x)), fill = cell.label))+ geom_bar()+theme_classic() +
   theme(text = element_text(size = 15), axis.text.x=element_text(angle=90))+ xlab('Assigned cell type') + ylab('Number of cells') +
    guides(fill = guide_legend(title = "Cell Phenotype")) 
  print(plot1)
  dev.off()

## remove the unknown cell types
df.filter <- df %>% filter(!grepl('unknown',cell.label))

pdf(paste(output_path,"BarFreq.allknown.pdf",sep=""),width =12, height = 6)
  plot1 <- ggplot(df.filter, aes(x=reorder(cell.label,cell.label,function(x)-length(x)), fill = cell.label))+ geom_bar()+theme_classic() +
   theme(text = element_text(size = 15), axis.text.x=element_text(angle=90, hjust = 1))+ xlab('Assigned cell type') + ylab('Number of cells') +
    guides(fill = guide_legend(title = "Cell Phenotype")) 
  print(plot1)
dev.off()


## plot the frequency 
df.filter <- df %>% filter(!grepl('unknown',cell.label))
# filter for only frequent double cell types
df.filter <- df.filter %>% group_by(cell.label) %>% dplyr::filter(n()< 500)

pdf(paste(output_path,"BarFreq.lowfreq.pdf",sep=""),width =12, height = 6)
  plot1 <- ggplot(df.filter, aes(x=reorder(cell.label,cell.label,function(x)-length(x)), fill = cell.label))+ geom_bar()+theme_classic() +
   theme(text = element_text(size = 15), axis.text.x=element_text(angle=90, hjust = 1))+ xlab('Assigned cell type') + ylab('Number of cells') +
    guides(fill = guide_legend(title = "Cell Phenotype")) 
  print(plot1)
dev.off()




```


Figure 3 cluster annotation
Visualize and quantify correlation
Heatmap
Feature plots


```{r}
# output path for figures
output_path <- "/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/"


# visualize correlation with clusters
seu <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/9MBO/prepro_outsjan20-9000cells/Figure3/cluster_parameters/retro-louv-moreparm/retrotransLouvainSeuratObject60.Rds")

seu <- RunUMAP(seu,spread = 1, min.dist = 0.05, dims = 1:12)

# now look at the correlation assignments
cor <- read.csv("/Users/rhalenathomas/Documents/Projects_Papers/PhenoID/ForFigures/Corr/corr_celltypes.csv")

# add the predicted correlation cell types to the seurat object
seu <- AddMetaData(object=seu, metadata=cor$cell.label, col.name = 'cor.labels')
# check the labels
unique(seu$cor.labels)
# plot the labels on the UMAP

#Figure S13 A
png(paste(output_path,"UMAPcorlabels.png"), width = 1100, height = 500)
DimPlot(seu, group.by = 'cor.labels', label = TRUE, repel = TRUE)
dev.off()

# Figure S13B 
# Bar chart of the cell types in the different clusters
# get the number of cells with each predictions per cluster
cor.lables <- as.data.frame(table(seu$RNA_snn_res.0.7, seu$cor.labels))
pr.cor.lables <- as.data.frame(prop.table(table(seu$RNA_snn_res.0.7, seu$cor.labels)))

# rename the df
colnames(cor.lables) <- c("Cluster","Predicted.Cell.Type","Number.Cells")


pdf(paste(output_path,"BarcorlabelsbyCluster.pdf"), width = 10, height = 3)
ggplot(cor.lables, aes(y = Number.Cells, x =Cluster, fill = Predicted.Cell.Type)) + geom_bar(position = "stack", stat= "identity") +
  theme_classic() +
   theme(text = element_text(size = 15), axis.text.x=element_text(angle=90, hjust = 0))+ xlab('Cluster Number') + ylab('Number of cells') +
    guides(fill = guide_legend(title = "Correlation Predicted Cell Type")) 
dev.off()

# try to filter out the unknown
df.filter <- cor.lables %>% filter(!grepl('unknown',Predicted.Cell.Type))

# Figure S13C
pdf(paste(output_path,"BarcorlabelsbyCluster.rm.unknown.pdf"), width = 10, height = 3)
ggplot(df.filter, aes(y = Number.Cells, x =Cluster, fill = Predicted.Cell.Type)) + geom_bar(position = "stack", stat= "identity") +
  theme_classic() +
   theme(text = element_text(size = 15), axis.text.x=element_text(angle=90, hjust = 0))+ xlab('Cluster Number') + ylab('Number of cells') +
    guides(fill = guide_legend(title = "Correlation Predicted Cell Type")) 
dev.off()

# create a table with the most frequent cell type prediction ignoring unknown
top.cells <- df.filter  %>% group_by(Cluster) %>% top_n(3, Number.Cells)

top.cell <- df.filter  %>% group_by(Cluster) %>% top_n(1, Number.Cells)
# put in excel sheet to predict cell types


### visualize expression 

# feature plots
# Figure S14
png(paste(output_path,"FtUMAP9000cells.neuron.png"), width = 1100, height = 200)
FeaturePlot(seu, features = c("CD24","CD56","CD29","CD15","CD71"), slot = 'scale.data',min.cutoff = 'q3', max.cutoff ='q97', ncol = 5)
dev.off()

png(paste(output_path,"FtUMAP9000cells.astro.png"), width = 1100, height = 200)
FeaturePlot(seu, features = c("CD44","GLAST","AQP4","HepaCAM","CD133"), slot = 'scale.data',min.cutoff = 'q3', max.cutoff ='q97', ncol = 5)
dev.off()


png(paste(output_path,"FtUMAP9000cells.olig.png"), width = 900, height = 200)
FeaturePlot(seu, features = c("O4","CD140a","CD184"), slot = 'scale.data',min.cutoff = 'q3', max.cutoff ='q97', ncol = 5)
dev.off()

Idents(seu) <- 'RNA_snn_res.0.7'
png(paste(output_path,"UMAP9000cell.clusters07.png"), width = 500, height = 300)
DimPlot(seu, label = TRUE, repel = TRUE, label.size = 5) + NoLegend()
dev.off()


#### now make the heatmap for these clusters to annotate

AB <- c("CD24","CD56","CD29","CD15","CD184","CD133","CD71","CD44","GLAST","AQP4","HepaCAM", "CD140a","O4")

# Figure S15

pdf(paste(output_path,"HM.9000.cluster07.pdf"),width = 10, height = 6)
Idents(seu) <- 'RNA_snn_res.0.7'
DoHeatmap(seu, features = AB, size= 6,slot = "scale.data", disp.max = 2, disp.min = -1.5, angle = 0) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 15))
dev.off()


```


Get the cell counts

```{r}

table(seu$Batch)
# total cells 
# total cells 73578

```


Cluster annotation of the 9000 cells from 9 hMOs

```{r}
# read in the annotated object
seu <- readRDS("/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/PaperFigures/Seu9000annot.08072021.RDS")


# more subgroups annotated
Idents(seu) <- "RNA_snn_res.0.7"
cluster.ids <- c("Unknown","Mixed","Neurons 1","Radial Glia 1","Epithelial","Astrocytes 1",
                 "Neurons 2","Astrocytes 2","Astrocytes 3","Astrocytes mature","Neurons 3","NPC",
                 "Radial Glia 2","Radial Glia 3","Endothelial",
                 "Oligodendrocytes","Stem-like 1","Stem-like 2", "Neural stem")

names(cluster.ids) <- levels(seu)
seu <- RenameIdents(seu, cluster.ids)
seu$subgroups <- Idents(seu)

# 19 levels - every cluster is it's own subgroup
# change the order of the cell types on the legend of the umap
cell.type.order <- c("Astrocytes 1", "Astrocytes 2","Astrocytes 3","Astrocytes mature",
                     "Radial Glia 1","Radial Glia 2","Radial Glia 3",
                     "Epithelial","Endothelial",
                     "Neural stem","NPC","Neurons 1","Neurons 2","Neurons 3",
                     "Oligodendrocytes","Stem-like 1","Stem-like 2",
                     "Mixed","Unknown")

cell.type.order <- rev(cell.type.order)

# colour order to match cell type order
clust.colours <- c("chocolate1","chocolate2","chocolate3","orangered",
                   "lightsalmon", "pink","lightpink3",
                   "steelblue3","deepskyblue",
                   "plum","plum3","purple","orchid2","mediumpurple2",
                   "seagreen3","tomato3","tomato4","burlywood3","grey90")
# Figure S16 
pdf(paste(output_path,"UMAP.9000.subgroups.pdf"),width = 15, height = 8)
DimPlot(seu, order = cell.type.order, cols = clust.colours, shuffle = TRUE, 
        raster=FALSE, pt.size = 0.1, label = FALSE) +
  theme(legend.text = element_text(size=24), axis.title.y = element_text(size=24), 
        axis.title.x = element_text(size=24), axis.text.y = element_text(size =24),
        axis.text.x = element_text(size =24))
dev.off()


# matching heatmap
levels(seu) <- c("Astrocytes 1", "Astrocytes 2","Astrocytes 3","Astrocytes mature",
                     "Radial Glia 1","Radial Glia 2","Radial Glia 3",
                     "Epithelial","Endothelial",
                     "Neural stem","NPC","Neurons 1","Neurons 2","Neurons 3",
                     "Oligodendrocytes","Stem-like 1","Stem-like 2",
                     "Mixed","Unknown")

pdf(paste(output_path,"HM9000.subtypes.08072022.pdf"),width = 8, height = 5)
DoHeatmap(seu, features = AB, size= 6,slot = "scale.data", group.colors = clust.colours, disp.max = 2, disp.min = -1.5,
          angle = 90) + scale_fill_gradientn(colors = c("#154c79", "#eeeee4", "#e28743")) + 
  theme(axis.text.y = element_text(size = 15))
dev.off()


saveRDS(seu, "/Users/rhalenathomas/Documents/Data/FlowCytometry/PhenoID/Analysis/PaperFigures/Seu9000annot.08072021.RDS")


```





